ALTER TABLE post
    MODIFY COLUMN model TEXT NOT NULL ;

ALTER TABLE post
    MODIFY COLUMN year INTEGER NOT NULL ;

ALTER TABLE post
    MODIFY COLUMN color TEXT NOT NULL ;

ALTER TABLE post
    MODIFY COLUMN engine TEXT NOT NULL ;


